name: qm_gnn

channels:
  - conda-forge
  - rdkit

dependencies:
  - tqdm=4.62
  - pip=21.3
  - tensorflow=2.6
  - scipy=1.7
  - pandas=1.3
  - scikit-learn=1.0
  - rdkit=2021.09
  - numpy=1.19
  - ipykernel=6.29
  - pip:
      - qmdesc
